# Basic site setup
title: HPE Labs
author: HPE Labs
description: HPE labs content for automation, DevOps, and hands-on infrastructure tutorials.
accent_colour: "#acacac"
theme_version: 1.0.16
url: https://hpelabs.github.io
baseurl: ""

# Optional native feature customisation (delete to turn off)
table_of_contents_header: "Jump to:"
table_of_contents_collapsible: true
post_end_promo: <i><b>Enjoyed this article? Discover more on the <a href="https://developer.hpe.com/">HPE Developer Community</a> site,<br> your hub for all HPE software-related content!</b></i>
replace_read_time_with_word_count: false
show_excerpts_html: true
open_external_links_in_new_tab: true

# Third party feature customisation (delete to turn off)
# giscus_repo:
# giscus_repo_id:
# giscus_category:
# giscus_category_id:
# kofi_id: internethistory
# kofi_button_text: Tip on Ko-fi
# kofi_floating_text: Tip / Suggest

# Network site picker
network:

# Social / dark mode settings
minima:
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/hpelabs" }
    - { platform: rss, user_url: "/feed.xml", user_title: "RSS Feed" }
 
  #   - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #   - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #   - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #   - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
  #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #   - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #   - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #   - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #   - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

###
# Below here probably doesn't need changing #
###

# Site settings
permalink: /:title/
timezone: Europe/Paris
title-logo: #/assets/images/favicon/favicon-32x32.png

# Default front matter for all lab-guide posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      hidden: true
      hide_header: true
      hide_footer: true
      hide_related_posts: true
      hide_comments: true
      hide_breadcrumbs: true
      hide_post_meta: true


# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Pagination settings
paginate: 5
paginate_path: page/:num/

# Syntax highlighter settings
kramdown:
  syntax_highlighter_opts:
    default_lang: kotlin
    guess_lang: true

# New fields not defaulted by jekyll-new with the minima theme
# Add a copyright. A copyright symbol and year will be added automatically
# copyright: Company name, Inc.
copyright: "Hewlett Packard Enterprise"